#!/bin/bash
#PBS -l nodes=2:ppn=12
#PBS -l walltime=0:01:00
#PBS -q batch
#PBS -N run_first
#PBS -j oe
#PBBS -V

cd ~/Project

mpiexec -np 2 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./countingSortParallel.cx
